apiVersion: v1
kind: Service
metadata:
  name: weather-service
  labels:
    app: weather                          #  ServiceMonitor 대상 선정용
spec:
  type: ClusterIP
  ports:
  - name: http                            #  ServiceMonitor 포트 지정용
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    app: weather