
apiVersion: keda.sh/v1alpha1
kind: ScaledObject 
metadata:
  name: tourist-service-scaler 
  namespace: {{ .Values.keda.namespace | default "jit-hub" }}

spec:
  scaleTargetRef:
    name: tourist-service     # jit-hub-app의 Deployment 이름과 일치하여 합니다.
    kind: Deployment
  minReplicaCount: {{ .Values.keda.minReplicaCount | default 1 }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount | default 5 }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod | default 300 }}

  triggers:
  - type: prometheus
    metadata:
    # kube-prometheus-stack 차트의 Prometheus 서비스명
      serverAddress: {{ .Values.keda.serverAddress }}
      metricName: tourist_request_rate
      # 전체 요청 수를 기록하는 메트릭에서 tourism--service 라는 앱의 1분 동안의 데이터만 가져오기
      query: |                            
        sum(rate(http_requests_total{job="tourist-service"}[1m]))    
      threshold: {{ .Values.keda.threshold | default "10" | quote }}        # 임계값 